pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // [P68-1] Naver Maps SDK (com.naver.maps:map-sdk)
        maven { url 'https://repository.map.naver.com/archive/maven' }
    }
}
rootProject.name = "ImuLocalApp"
include ':app'
